name: Test

on:
  pull_request:
    branches: [main]


jobs:
  build:
    name: build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Check out
        uses: actions/checkout@v2.4.0
      - run: npm ci
      - run: npm run build
      - run: npm test